name: build
on: 
  push: 
     branches: [ master ] 
  pull_request: 
     branches: [ master ]

jobs: 
  test: 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install Flutter 
      uses: subosito/flutter-action@v1.3.2
      
    - name: Install dependencies 
      run: flutter pub get
    
    - name: Dart formatting
      run: flutter dartfmt ./
      
    - name: Test app 
      run: flutter test --coverage
      
    - name: Upload coverage to Codecov 
      uses: codecov/codecov-action@v1 
      with: 
        token: ${{ secrets.CODECOV_TOKEN }} 
        file: coverage/lcov.info

  package-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: axel-op/dart-package-analyzer@v3
        # set an id for the current step
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # You can then use this id to retrieve the outputs in the next steps.
      # The following step shows how to exit the workflow with an error if the total score in percentage is below 50:
      - name: Check scores
        env:
          # NB: "analysis" is the id set above. Replace it with the one you used if different.
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $PERCENTAGE < 50 ))
          then
            echo Score too low!
            exit 1
          fi
